# Generated by Django 4.0.5 on 2022-06-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_warehouse_warehouse_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '负责库房', 'verbose_name_plural': '员工管理'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别'),
        ),
    ]
