# Generated by Django 4.0.5 on 2022-06-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_staff_options_alter_staff_staff_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
