# Generated by Django 4.0.5 on 2022-06-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
