# Generated by Django 4.0.5 on 2022-06-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=32)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('recent_time', models.DateTimeField()),
                ('credibility', models.CharField(max_length=256)),
                ('job', models.CharField(max_length=256)),
                ('industry', models.CharField(max_length=256)),
                ('place', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
    ]
