# Generated by Django 4.0.5 on 2022-06-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '供应商管理',
                'verbose_name_plural': '供应商管理',
            },
        ),
    ]
