# Generated by Django 4.0.5 on 2022-06-21 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(max_length=256, verbose_name='供货类别'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=256, verbose_name='供货城市'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=128, verbose_name='供应商名称'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=256)),
                ('Signed_time', models.DateTimeField()),
                ('price', models.IntegerField(default=0)),
                ('order_status', models.IntegerField(choices=[(1, '签订'), (2, '未签订'), (3, '违约')], default='签订')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
            ],
            options={
                'verbose_name': '订单管理',
                'verbose_name_plural': '订单管理',
            },
        ),
    ]
